In [23]:
import numpy as np

np.linspace(1,1,100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
import numpy as np
n_random_ = np.random.random((100,100))
print(n_random_)



[[0.31500569 0.59901445 0.98298716 ... 0.76684024 0.39815539 0.94444218]
 [0.56217865 0.03534242 0.79587756 ... 0.02884896 0.89873589 0.10758472]
 [0.82959602 0.77590632 0.35461081 ... 0.31689676 0.86258394 0.03861842]
 ...
 [0.40189881 0.32608962 0.78351346 ... 0.55451487 0.20197546 0.22541577]
 [0.55686357 0.98366393 0.98865608 ... 0.0683651  0.32810289 0.92681314]
 [0.9951832  0.70471751 0.77542862 ... 0.73027358 0.48456164 0.80937695]]


In [32]:
m_random = np.random.random((100,100))*100
print(m_random)



[[21.41910656 83.27034118 49.15953993 ...  7.8699916  71.00441626
  62.1273626 ]
 [86.0914639  80.9486792  39.39467143 ...  5.34544792 32.75347337
   7.19241842]
 [ 3.43096783 50.88336641 78.04246088 ... 98.25744193 43.57747914
  69.79120509]
 ...
 [ 2.20527728 58.52236515 15.8952052  ... 36.66941676 42.99984998
  80.21472783]
 [21.91209542 61.64465152 19.28266324 ... 22.68992976 70.32686644
  73.6724461 ]
 [44.70933676 64.16997146 35.00043955 ... 51.6842559  86.49370227
  86.71497877]]
